version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/www"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(www)"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/app"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(app)"
    open-pull-requests-limit: 10
