export type Section = {
  id: string;
  title: string;
  description: string;
  order: number;
  isLocked?: boolean;
  isReview?: boolean;
};

export const sections: Section[] = [
  {
    id: "basics",
    title: "Basics",
    description: "Learn the most common words",
    order: 1,
    isLocked: false,
  },
  {
    id: "objects",
    title: "Objects",
    description: "Learn words for everyday objects",
    order: 2,
    isLocked: false,
  },
  {
    id: "animals",
    title: "Animals",
    description: "Learn words for different animals",
    isLocked: false,
    order: 3,
  },
  {
    id: "fruits",
    title: "Fruits",
    description: "Learn words for different fruits",
    isLocked: false,
    order: 4,
  },
  {
    id: "vegetables",
    title: "Vegetables",
    description: "Learn words for different vegetables",
    isLocked: false,
    order: 5,
  },
  {
    id: "review-1",
    title: "Progress Check",
    description: "Review the first set of words",
    isLocked: true,
    order: 6,
    isReview: true,
  },
  {
    id: "numbers",
    title: "Numbers",
    description: "Learn basic numbers",
    order: 7,
    isLocked: true,
  },
  {
    id: "counting",
    title: "Counting",
    description: "Practice counting different objects",
    order: 8,
    isLocked: true,
  },
  {
    id: "actions",
    title: "Actions",
    description: "Learn common action verbs",
    order: 9,
    isLocked: true,
  },
  {
    id: "household",
    title: "Household",
    description: "Learn words for household items",
    order: 10,
    isLocked: true,
  },
  {
    id: "places",
    title: "Places",
    description: "Learn words for different places",
    order: 11,
    isLocked: true,
  },
  {
    id: "review-2",
    title: "Progress Check",
    description: "Review your growing vocabulary.",
    isLocked: true,
    order: 12,
    isReview: true,
  },
  {
    id: "sentences-1",
    title: "Action Sentences",
    description: "Learn sentences about people doing things",
    order: 13,
    isLocked: true,
  },
  {
    id: "sentences-2",
    title: "Possession Sentences",
    description: "Learn to express what people have or own",
    order: 14,
    isLocked: true,
  },
  {
    id: "sentences-3",
    title: "More Sentences",
    description: "Practice more complex sentences",
    order: 15,
    isLocked: true,
  },
  {
    id: "feelings",
    title: "Feelings",
    description: "Learn words for different feelings",
    order: 16,
    isLocked: true,
  },
  {
    id: "clothing",
    title: "Clothing",
    description: "Learn clothing vocabulary",
    order: 17,
    isLocked: true,
  },
  {
    id: "review-3",
    title: "Progress Check",
    description: "Review the final word set.",
    isLocked: true,
    order: 18,
    isReview: true,
  },
  {
    id: "food",
    title: "Food",
    description: "Learn words for different foods",
    order: 19,
    isLocked: true,
  },
  {
    id: "people-jobs",
    title: "People and Jobs",
    description: "Learn words for what people do",
    order: 20,
    isLocked: true,
  },
  {
    id: "kitchen",
    title: "Kitchen",
    description: "Learn words for different kitchen items",
    order: 21,
    isLocked: true,
  },
  {
    id: "locations",
    title: "Where Are Things?",
    description: "Learn words for different locations",
    order: 22,
    isLocked: true,
  },
  {
    id: "sentences-4",
    title: "Asking Sentences",
    description: "Learn how to ask for things",
    order: 23,
    isLocked: true,
  },
  {
    id: "review-4",
    title: "Progress Check",
    description: "Review the final word set.",
    isLocked: true,
    order: 24,
    isReview: true,
  },
  {
    id: "countries",
    title: "Countries",
    description: "Learn words for different countries",
    order: 25,
    isLocked: true,
  },
];
